# Generated by Django 2.0.3 on 2018-05-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_auto_20180527_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('lightValue', models.IntegerField()),
                ('climatValue', models.IntegerField()),
            ],
        ),
    ]
